### ISSUE TITLE
request: provide a link to my swift version

### ISSUE THREAD

**Issue by ConfusedVorlon** [leighmcculloch/AppSandboxFileAccess#11]
My Swift version is here
https://github.com/ConfusedVorlon/SwiftySandboxFileAccess

It would be great if you could provide a link to that in your Readme for people who prefer the Swift API

thanks again for the great bit of code

**Comment by leighmcculloch** [comment]
Good idea! I added a badge for your swift fork to the top of the readme in e2bd2910f1846eea13cb2e00bc4945e96262c705.

**Comment by ConfusedVorlon** [comment]
thanks
