### ISSUE TITLE
Does this work in Yosemite?

### ISSUE THREAD

**Issue by tarngerine** [leighmcculloch/AppSandboxFileAccess#3]
I've been trying to use this but it looks like it only works the first time in a specific folder, and the persisting doesn't actually work — subsequent tries sandboxd just gives a deny file-write-create (or whatever) error

Looks like this was updated last 8 months ago, not sure if it still works for you or it's just me

**Comment by leighmcculloch** [comment]
Hi Julius, thanks, I haven't tested this on Yosemite, but will look into
what might not be working.

**Comment by tarngerine** [comment]
If I pass false for persist it'll work but will prompt the user every time. Passing true seems to make it not work on subsequent times in the same folder. 


Thanks!

**Comment by vslavik** [comment]
FWIW, I'm using AppSandboxFileAccess ([fork](http://github.com/vslavik/AppSandboxFileAccess) with inconsequential changes) in production and everything works as expected on Yosemite (and yes, I just re-checked again to be sure).

**Comment by tarngerine** [comment]
I see. Thanks for checking. Must be an issue on my side.

**Comment by leighmcculloch** [comment]
There is an issue with stale bookmarks in the current version. Stale bookmarks are not being renewed correctly. Working on a fix.

**Comment by tarngerine** [comment]
awesome. thanks!

**Comment by leighmcculloch** [comment]
The fix for stale bookmarks is in version 1.0.14
