### ISSUE TITLE
Custom NSOpenPanel action?

### ISSUE THREAD

**Issue by liufsd** [leighmcculloch/AppSandboxFileAccess#6]
Hi,I want to custom NSOpenPanel when askPermissionForURL, action such as new folder button on panel.
'openPanel setCanCreateDirectories:YES'
And I can create new folder ,then write new file on this folder.

**Comment by leighmcculloch** [comment]
It's not possible to do that at the moment, but it makes sense for the `NSOpenPanel` that gets created to be configurable. How about we add properties for each of the configurable elements of `NSOpenPanel`, and then use those properties in [askPermissionForURL](https://github.com/leighmcculloch/AppSandboxFileAccess/blob/465eaab70a763f1edd5328eb2664c961dfa52650/AppSandboxFileAccess/Classes/AppSandboxFileAccess.m#L101-L109) like we do already with the `message`, `prompt`, and `title`.

**Comment by liufsd** [comment]
I have do it by myself.~
Thanks.

**Comment by leighmcculloch** [comment]
Feel free to open a pull request with the change 😄.

**Comment by liufsd** [comment]
I will pull request later~
